services:
  db:
    image: postgres:16.4
    restart: always
    environment:
      POSTGRES_DB: voxellery_local
      POSTGRES_USER: voxellery
      POSTGRES_PASSWORD: voxtestellerytest
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  localstack:
    image: localstack/localstack:3.6.0
    environment:
      - SERVICES=s3
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - ./localstack_setup.sh:/etc/localstack/init/ready.d/script.sh
      - ./.localstack:/var/lib/localstack # Save S3 data locally for testing purposes
    ports:
      - "4566:4566"

volumes:
  pgdata:
